export const LOADING_SYSTEM_TEXT = [
  "[BOOT SEQUENCE INITIATED]",
  "Verifying core BIOS firmware... [OK]",
  "Initializing Neurolink Interface v4.7.21... [SUCCESS]",
  "Decoding Neural Grid Patterns... [COMPLETE]",
  "Loading Quantum Buffer Modules... [LOADED]",
  "Establishing Synthex Protocol v2.3.9... [LINKED]",
  "CyberDeck Firmware Checksum: [VALID]",
  "Accessing Memory Grid: Sector 045x-Delta... [ONLINE]",
  "Authenticating User ID: ∞-01-AE... [AUTHORIZED]",
  "SYSTEM SCAN INITIATED",
  ">> BioFirewall Integrity... [SECURE]",
  ">> Nanite Injection Channels... [STABLE]",
  ">> Data Spike Resistance... [OPTIMAL]",
  ">> Quantum Key Encryption (QKE) Status... [ACTIVE]",
  "Scanning Memory Nodes...",
  ">> Node-01: [UNSTABLE - RECOVERING]",
  ">> Node-02: [STABLE]",
  ">> Node-03: [STABLE]",
  ">> Node-04: [OFFLINE - REBOOTING]",
  "Loading Retinal Overlay Interface... [ACTIVE]",
  "Syncing Optical Implants... [SYNCHRONIZED]",
  "Initializing Neural Uplink Control... [CONNECTED]",
  "Spooling Data Threads... [100% SYNCHED]",
  "System Drives Detected:",
  ">> DRIVE-01 [QUANTUM CORE STORAGE] [142.8 TB FREE]",
  ">> DRIVE-02 [EXO-MEMORY ARRAY] [97% FULL]",
  ">> DRIVE-03 [BLACK VAULT DATA LOCKER] [ENCRYPTED]",
  "Bootstrapping AI Companion: CYBER-GHOST v3.6.12... [READY]",
  "Establishing Secure Uplink with GridNet... [CONNECTED]",
  "Running Digital Cloak Protocol... [ENGAGED]",
  "Critical Subsystems Status:",
  ">> ElectroPulse Deflectors... [ARMED]",
  ">> Signal Nullification Grid... [ONLINE]",
  ">> Cortex Drive - Synaptic Link... [STABLE]",
  "Retrieving Encrypted Data Packets...",
  ">> Packet ID: #X89021 [DECRYPTED]",
  ">> Packet ID: #F98471 [QUARANTINED]",
  ">> Packet ID: #X22B90 [LOADED]",
  "Activating NeuroCommand Interface... [BOOTING]",
  "Injecting Synaptic Signal Tracers... [MAPPED]",
  "Spooling Memory Core Routines... [OPTIMIZED]",
  "Checking Power Grid Stability...",
  ">> Power Cell 01 [95% - OPERATIONAL]",
  ">> Power Cell 02 [90% - OPERATIONAL]",
  ">> Power Cell 03 [DISCONNECTED - OFFLINE]",
  "Loading Visual Augmentation Module... [ONLINE]",
  "Initializing HoloDeck Environment... [SUCCESS]",
  "DataSync Beacon Protocol... [LOCKED IN]",
  "Uplink Node Status: [GREEN ZONE]",
  "EXECUTING STARTUP MACRO [LOKI-23-INIT]",
  "Overclocking CyberNeural Pathways... [ENHANCED MODE ACTIVATED]",
  "Virtual Cortex Defense Shield... [STANDBY]",
  "SYSTEM BOOT COMPLETE. WELCOME, USER.",
];

export const SECURITY_PROTOCOL = [
  "[SECURITY PROTOCOL INITIALIZED]",
  "Decrypting Access Keys... [SUCCESS]",
  "Firewall Node #7: [BREACHED]",
  "Deploying Counter-Intrusion Algorithm... [ENGAGED]",
  "Reinforcing DataShield... [ACTIVE]",
  "Virus Signature Detected: CODE-23X9... [NEUTRALIZED]",
  "Quantum Barrier Stabilized... [SECURE]",
];

export const DATA_STREAM_TOP = [
  "[DATA STREAM INCOMING]",
  "Verifying Data Hash... [MATCH]",
  "Packet ID: #F39210... [RECEIVED]",
  "Source IP: [UNKNOWN NODE]",
  "Injecting Trace Protocol... [ACTIVE]",
  "Echo Return Signal... [LOST]",
  "Suspicious Activity Logged... [MONITORING]",
];

export const DATA_STREAM_BOTTOM = [
  "[RECEIVING DATA]",
  "Verifying Data Integrity... [DONE]",
  "Packet ID: #F39210... [DONE]",
  "FIREWALL ACTIVATED: [DONE]",
  "Injecting Trace Protocol... [DONE]",
  "GridNet Uplink Secured... [DONE]",
  "Suspicious Activity Logged... [DONE]",
];

export const NODE_CONNECTION = [
  "[NODE CONNECTION ESTABLISHED]",
  "Handshaking Protocol Initiated... [OK]",
  "GridNet Uplink Secured... [STABLE]",
];

export const MALWARE_SCAN = [
  "[MALWARE SCAN INITIATED]",
  "Analyzing Memory Blocks... [27 INFECTED SECTORS FOUND]",
  "Deploying Heuristic Cleanse Routine... [IN PROGRESS]",
  "Sector 045x-Delta [CLEAN]",
  "Sector 12-Beta [REPAIRED]",
  "Sector 93-Gamma [QUARANTINED]",
  "Rootkit Tracer... [ENGAGED]",
];

export const ENCRYPTION_CHECK = [
  "[SYSTEM ENCRYPTION CHECK]",
  "Verifying Quantum Cipher... [VALID]",
  "Neural Lock Code... [RECOGNIZED]",
  "Data Vault Access... [AUTHORIZED]",
  "Access Log Timestamp: 23:15:47",
  "Monitoring Suspicious Activity... [ALERT TRIGGERED]",
  "Countermeasures Deployed... [ACTIVE]",
];

export const BIOFEED_INTERFACE = [
  "[BIOFEED INTERFACE ONLINE]",
  "Pulse Sync Calibration... [ALIGNED]",
  "Heart Rate Monitor... [NORMAL]",
  "Cerebral Signal Integrity... [STABLE]",
  "Oxygen Flow Stabilizer... [OK]",
  "BioFirewall Check... [SECURE]",
  "Activating Emergency Pulse Shield... [ARMED]",
];

export const REMOTE_ACCESS = [
  "[REMOTE ACCESS DETECTED]",
  "Source Node: [UNREGISTERED DEVICE]",
  "Firewall Spike Protocol... [DEPLOYED]",
  "IP Redirecting Sequence... [ACTIVE]",
  "Data Decoy Injected... [SUCCESS]",
  "Surveillance Log Entry #58923... [LOGGED]",
  "Uplink Signal Encrypted... [SECURE]",
];

export const AI_COMPANION = [
  "[AI COMPANION LOADED]",
  "CYBER-GHOST v4.2.8 Initialized... [READY]",
  "Analyzing Data Streams... [ACTIVE]",
  "Identifying Malicious Code Patterns... [IN PROGRESS]",
  "Virtual Cortex Mapping... [MAPPED]",
  "Injecting Counter-Code Subroutine... [DEPLOYED]",
  "System Integrity Scan... [100%]",
];

export const EXTERNAL_SIGNAL = [
  "[EXTERNAL SIGNAL DETECTED]",
  "Frequency: 88.7 Hz... [INTERCEPTED]",
  "Signal Origin: [REDACTED]",
  "Data Injection Attempt... [BLOCKED]",
  "Firewall Intrusion Signature Logged... [ID: X3901]",
  "Countermeasure Protocol... [ARMED]",
];

export const MEMORY_GRID_TOP = [
  "[MEMORY GRID STATUS]",
  "Sector 01-A... [STABLE]",
  "Sector 02-B... [DAMAGED - RECOVERING]",
  "Sector 03-C... [INTEGRITY CHECK]",
  "Root Structure Analysis... [REPAIRED]",
  "NeuronPulse Backup... [ENGAGED]",
  "DataSync Threshold... [OPTIMIZED]",
];

export const MEMORY_GRID_BOTTOM = [
  "[MEMORY GRID STATUS]",
  "Sector 01-A... [STABLE]",
  "Sector 02-B... [DAMAGED - RECOVERING]",
  "Sector 03-C... [INTEGRITY CHECK]",
  "Root Structure Analysis... [REPAIRED]",
];

export const BOOT_SEQUENCE_LIST = [
  "$ nuxt dev",
  "Nuxt 3.15.4 with Nitro 2.11.8",
  "nuxi  8:00:11",
  "8:00:11",
  "➜ Local:    http://localhost:3000/",
  "➜ Network:  use --host to expose",
  "ℹ Using default Tailwind CSS file",
  "nuxt:tailwindcss 8:00:12",
  "➜ DevTools: press Shift + Alt + D in the browser (v1.7.0)",
  "8:00:13",
  "ℹ Nuxt Icon server bundle mode is set to local",
  "8:00:14",
  "✔ Nuxt Icon discovered local-installed 1 collections: heroicons",
  "8:00:16",
  "✔ Vite client built in 36ms",
  "8:00:17",
  "✔ Vite server built in 1300ms",
  "8:00:18",
  "✔ Nuxt Nitro server built in 1067ms",
  "nitro 8:00:20",
  "ℹ Vite client warmed up in 371ms",
  "8:00:21",
  "ℹ Vite server warmed up in 2963ms",
  "[    0.000000] InitOS Kernel v1.7.3 initializing...",
  "[    0.002134] Mounting primary file system...",
  "[    0.004678] RootFS mounted at /dev/initdisk0",
  "[    0.006512] Detected 4 CPU cores @ 3.20GHz",
  "[    0.007845] Initializing virtual memory subsystem...",
  "[    0.009234] VM subsystem initialized",
  "[    0.010390] Starting systemd-like service manager...",
  "[    0.012589] [ OK ] Service manager started successfully",
  "[    0.013420] Mounting /proc and /sys...",
  "[    0.015221] [ OK ] /proc mounted",
  "[    0.016789] [ OK ] /sys mounted",
  "[    0.018332] Loading kernel modules...",
  "[    0.020210] [FAILED] Failed to load module 'hypernet.ko'",
  "[    0.020450] See '/var/log/initos/hypernet.log' for details",
  "[    0.022190] Loading remaining kernel modules...",
  "[    0.023000] [ OK ] All required modules loaded",
  "[    0.025340] Initializing device manager...",
  "[    0.026754] [ OK ] Device manager ready",
  "[    0.028100] Starting InitOS Network Stack...",
  "[    0.029670] [ OK ] Loopback interface up (lo)",
  "[    0.030812] [ OK ] Interface eth0 configured via DHCP",
  "[    0.032399] Syncing system clock with NTP...",
  "[    0.035602] [ OK ] Clock synchronized: 2025-04-16 10:42:17",
  "[    0.038210] Starting user session services...",
  "[    0.040321] [ OK ] Session services initialized",
  "[    0.043001] InitOS boot complete. Welcome to InitOS v1.7.3!",
];

export const FILES_LIST = [
  "/data/black_vault/encrypted_logs_045x.dat",
  "/sys/core/kernel_patch_v3.4.2.bin",
  "/net/gridnet/pulse_monitor.sys",
  "/usr/bin/neuro_link_driver_v1.12.dll",
  "/backdoor/infiltration_protocols/latchkey-9x.exe",
  "/memory/core_backup/snapshot_2025-03-16.img",
  "/security/firewall_nodes/node_07.cfg",
  "/usr/local/bin/cyber_ghost_v4.2.8.exe",
  "/data/bio_interface/sync_calibration.log",
  "/logs/remote_access_attempts/entry_58923.txt",
  "/ai/cortex_map/virtual_cortex_045x.map",
  "/net/signal_traps/signal_x3901.pkt",
  "/backup/mem_grid/sector_02-B.repair",
  "/temp/nanite_cache/pulse_shield_v2.temp",
  "/logs/virus_signatures/code_23X9.sig",
  "/config/quantum_barrier/protocols/qb-05.xml",
  "/biofeed/stabilizers/oxygen_flow.cal",
  "/security/surveillance_logs/log_010223.dat",
  "/config/digital_cloak/dc_v3.1.sys",
  "/data/holo_deck/env_23B.sav",
  "/sys/boot/primary_bootloader.bin",
  "/net/mesh_networks/grid_77x.sys",
  "/security/encryption_keys/key_vault.kdbx",
  "/usr/bin/synaptic_stim_driver_v2.dll",
  "/backup/intrusion_detection/idp_v5.9.bak",
  "/temp/decoy_data/spike_trace.temp",
  "/config/defense_matrix/dm_core.cfg",
  "/data/memory_shard/shard_0043.img",
  "/logs/cyber_attack_log_4021.txt",
  "/usr/local/bin/neural_map_generator.exe",
  "/sys/core/quantum_protocol_v1.5.sys",
  "/net/signal_protection/frequency_shield.cfg",
  "/security/blacklist/ip_blacklist.cfg",
  "/data/archive/sector_93B_backup.zip",
  "/usr/bin/data_recovery_tool_v3.dll",
  "/logs/fail_safe_protocol/fsp_2204.log",
  "/config/holo_interface/holo_env_v2.sav",
  "/backup/nerve_implant_data/implant_34x.img",
  "/usr/bin/biotech_driver_v1.3.dll",
  "/temp/hack_attempt_trace/trace_log_3847.temp",
  "/config/neuro_latch/nl_core.sys",
  "/logs/emergency_protocols/emergency_23E.log",
  "/usr/local/bin/optical_shield_v4.6.exe",
  "/data/secure_keyring/keyring_0923.kdbx",
  "/net/gridnet_uplink/uplink_trace_7788.sys",
  "/backup/data_snapshot/ds_2025_04_02.img",
  "/usr/bin/quantum_buffer_driver_v1.9.dll",
  "/logs/implant_sync_logs/sync_34A.log",
  "/config/data_harvest/dh_v2.3.sys",
  "/data/fusion_drive/fd_master_record.dat",
  "/usr/bin/virtual_memory_driver_v5.dll",
  "/config/infosec_protection/ip_guard_v4.sys",
];

export const LEFT_SIDE_TEXT = `· AAH-B03 · v.0000-234.233334.23 · Threat scanner enabled || This system is proprietary to CSG-Systems and employs state-of-the-art CORPO-CYBERWARE countermeasures. || Memory Integrity Check: PASSED · Quantum Firewall Status: ACTIVE · DataVault Sync: v.4.12.03 · Uplink Node Status: SECURED · BIOS Firmware: NEUROTECH-v7.1 · Encryption Layer: Q-CIPHER-5.2.9 · Sector Integrity Scan: 98% STABLE · Packet Monitoring Enabled: NODE_045X · Suspicious Activity Detected: LOGGED · TRACE ID: #F39A-442 · Memory Bank Capacity: 79% UTILIZED · System Pulse: SYNCED · Neural Lock Authentication: READY · Operating Kernel: CORE-NET V2.87 · Alert Protocols: ENGAGED`;
