export interface Portfolio {
  id: number;
  image: string;
  stack: { techName: string; imageUrl: string }[];
  prevTitleKey: string;
  titleKey: string;
  descriptionKey: string;
  repo: string;
  href?: string;
}

export const PORTFOLIO_PROJECTS: Portfolio[] = [
  {
    id: 1,
    image: "/img/apps/vue-form-latte.png",
    stack: [
      { techName: "Vue", imageUrl: "/tech-logos/vue.svg" },
      { techName: "TypeScript", imageUrl: "/tech-logos/typescript.svg" },
      { techName: "Vitest", imageUrl: "/tech-logos/vitest.svg" },
      { techName: "Tailwind", imageUrl: "/tech-logos/tailwind.svg" },
    ],
    prevTitleKey: "portfolio.projects.1.prevTitle",
    repo: "https://github.com/Lithos-hub/vue-form-latte",
    titleKey: "portfolio.projects.1.title",
    descriptionKey: "portfolio.projects.1.description",
  },
  {
    id: 2,
    image: "/img/apps/iUI.jpg",
    stack: [
      { techName: "Vue", imageUrl: "/tech-logos/vue.svg" },
      { techName: "TypeScript", imageUrl: "/tech-logos/typescript.svg" },
      { techName: "Tailwind", imageUrl: "/tech-logos/tailwind.svg" },
      { techName: "SCSS", imageUrl: "/tech-logos/sass.svg" },
    ],
    prevTitleKey: "portfolio.projects.2.prevTitle",
    href: "https://iui-app.netlify.app/",
    repo: "https://github.com/Lithos-hub/iUI",
    titleKey: "portfolio.projects.2.title",
    descriptionKey: "portfolio.projects.2.description",
  },
  {
    id: 3,
    image: "/img/apps/iOrbit.jpg",
    stack: [
      { techName: "React", imageUrl: "/tech-logos/react.svg" },
      { techName: "Three.js", imageUrl: "/tech-logos/three.svg" },
      { techName: "Tailwind", imageUrl: "/tech-logos/tailwind.svg" },
      { techName: "TypeScript", imageUrl: "/tech-logos/typescript.svg" },
    ],
    prevTitleKey: "portfolio.projects.3.prevTitle",
    href: "https://i-orbit.vercel.app/",
    repo: "https://github.com/Lithos-hub/iOrbit",
    titleKey: "portfolio.projects.3.title",
    descriptionKey: "portfolio.projects.3.description",
  },
  {
    id: 4,
    image: "/img/apps/iAdopt.jpg",
    stack: [
      { techName: "Next 13", imageUrl: "/tech-logos/next.svg" },
      { techName: "HTML", imageUrl: "/tech-logos/html.svg" },
      { techName: "CSS", imageUrl: "/tech-logos/css.svg" },
      { techName: "Tailwind", imageUrl: "/tech-logos/tailwind.svg" },
      { techName: "TypeScript", imageUrl: "/tech-logos/typescript.svg" },
      { techName: "OpenAI", imageUrl: "/tech-logos/openai.svg" },
      { techName: "MongoDB", imageUrl: "/tech-logos/mongo.svg" },
    ],
    prevTitleKey: "portfolio.projects.4.prevTitle",
    href: "https://i-adopt-landing-app.vercel.app/",
    repo: "https://github.com/Lithos-hub/iAdopt-LandingApp",
    titleKey: "portfolio.projects.4.title",
    descriptionKey: "portfolio.projects.4.description",
  },
  {
    id: 5,
    image: "/img/apps/infojobs.svg",
    stack: [
      { techName: "React", imageUrl: "/tech-logos/react.svg" },
      { techName: "HTML", imageUrl: "/tech-logos/html.svg" },
      { techName: "CSS", imageUrl: "/tech-logos/css.svg" },
      { techName: "SCSS", imageUrl: "/tech-logos/sass.svg" },
      { techName: "Tailwind", imageUrl: "/tech-logos/tailwind.svg" },
      { techName: "TypeScript", imageUrl: "/tech-logos/typescript.svg" },
      { techName: "Node", imageUrl: "/tech-logos/node.svg" },
      { techName: "Express", imageUrl: "/tech-logos/express.svg" },
      { techName: "OpenAI", imageUrl: "/tech-logos/openai.svg" },
    ],
    prevTitleKey: "portfolio.projects.5.prevTitle",
    href: "https://hackathon-infojobs-2023-lithoshub.netlify.app/",
    repo: "https://github.com/Lithos-hub/infojobs-hackathon",
    titleKey: "portfolio.projects.5.title",
    descriptionKey: "portfolio.projects.5.description",
  },
  {
    id: 6,
    image: "/img/apps/iPet.jpg",
    stack: [
      { techName: "React", imageUrl: "/tech-logos/react.svg" },
      { techName: "HTML", imageUrl: "/tech-logos/html.svg" },
      { techName: "CSS", imageUrl: "/tech-logos/css.svg" },
      { techName: "SCSS", imageUrl: "/tech-logos/sass.svg" },
      { techName: "TypeScript", imageUrl: "/tech-logos/typescript.svg" },
      { techName: "Vitest", imageUrl: "/tech-logos/vitest.svg" },
      { techName: "Tailwind", imageUrl: "/tech-logos/tailwind.svg" },
      { techName: "Node", imageUrl: "/tech-logos/node.svg" },
      { techName: "Express", imageUrl: "/tech-logos/express.svg" },
      { techName: "MongoDB", imageUrl: "/tech-logos/mongo.svg" },
    ],
    prevTitleKey: "portfolio.projects.6.prevTitle",
    href: "https://main--ipet-spa.netlify.app/",
    repo: "https://github.com/Lithos-hub/iPet-SPA",
    titleKey: "portfolio.projects.6.title",
    descriptionKey: "portfolio.projects.6.description",
  },
  {
    id: 7,
    image: "/img/apps/iMovies.jpg",
    stack: [
      { techName: "Vue 3", imageUrl: "/tech-logos/vue.svg" },
      { techName: "HTML", imageUrl: "/tech-logos/html.svg" },
      { techName: "CSS", imageUrl: "/tech-logos/css.svg" },
      { techName: "SCSS", imageUrl: "/tech-logos/sass.svg" },
      { techName: "TypeScript", imageUrl: "/tech-logos/typescript.svg" },
      { techName: "Vitest", imageUrl: "/tech-logos/vitest.svg" },
      { techName: "Tailwind", imageUrl: "/tech-logos/tailwind.svg" },
      { techName: "Node", imageUrl: "/tech-logos/node.svg" },
      { techName: "Express", imageUrl: "/tech-logos/express.svg" },
      { techName: "MongoDB", imageUrl: "/tech-logos/mongo.svg" },
    ],
    prevTitleKey: "portfolio.projects.7.prevTitle",
    href: "https://main--imovies-v2.netlify.app/",
    repo: "https://github.com/Lithos-hub/iMovies-v2-SPA",
    titleKey: "portfolio.projects.7.title",
    descriptionKey: "portfolio.projects.7.description",
  },
  {
    id: 8,
    image: "/img/apps/iCompose.jpg",
    stack: [
      { techName: "Vue 3", imageUrl: "/tech-logos/vue.svg" },
      { techName: "HTML", imageUrl: "/tech-logos/html.svg" },
      { techName: "CSS", imageUrl: "/tech-logos/css.svg" },
      { techName: "SCSS", imageUrl: "/tech-logos/sass.svg" },
      { techName: "Vitest", imageUrl: "/tech-logos/vitest.svg" },
      { techName: "TypeScript", imageUrl: "/tech-logos/typescript.svg" },
      { techName: "Tailwind", imageUrl: "/tech-logos/tailwind.svg" },
    ],
    prevTitleKey: "portfolio.projects.8.prevTitle",
    href: "https://icompose.netlify.app/",
    repo: "https://github.com/Lithos-hub/iCompose-v2",
    titleKey: "portfolio.projects.8.title",
    descriptionKey: "portfolio.projects.8.description",
  },
  {
    id: 9,
    image: "/img/apps/iCode.jpg",
    stack: [
      { techName: "Vue 3", imageUrl: "/tech-logos/vue.svg" },
      { techName: "HTML", imageUrl: "/tech-logos/html.svg" },
      { techName: "CSS", imageUrl: "/tech-logos/css.svg" },
      { techName: "SCSS", imageUrl: "/tech-logos/sass.svg" },
      { techName: "JavaScript", imageUrl: "/tech-logos/javascript.svg" },
    ],
    prevTitleKey: "portfolio.projects.9.prevTitle",
    href: "https://icode-playground-app.netlify.app/",
    repo: "https://github.com/Lithos-hub/iCode",
    titleKey: "portfolio.projects.9.title",
    descriptionKey: "portfolio.projects.9.description",
  },
  {
    id: 10,
    image: "/img/apps/iShop.jpg",
    stack: [
      { techName: "Vue 3", imageUrl: "/tech-logos/vue.svg" },
      { techName: "HTML", imageUrl: "/tech-logos/html.svg" },
      { techName: "CSS", imageUrl: "/tech-logos/css.svg" },
      { techName: "SCSS", imageUrl: "/tech-logos/sass.svg" },
      { techName: "JavaScript", imageUrl: "/tech-logos/javascript.svg" },
      { techName: "Firebase", imageUrl: "/tech-logos/firebase.svg" },
    ],
    prevTitleKey: "portfolio.projects.10.prevTitle",
    href: "https://ishop-app.netlify.app/",
    repo: "https://github.com/Lithos-hub/iShop",
    titleKey: "portfolio.projects.10.title",
    descriptionKey: "portfolio.projects.10.description",
  },
];
